# Arrays
* pip install array or pip3 install array
# type anaconda prompt

In [1]:
import array as arr

In [2]:
a=arr.array('i',[1,2,3,4,5])
b= arr.array('i',[6,7,8,9,10])

In [3]:
a

array('i', [1, 2, 3, 4, 5])

In [4]:
b

array('i', [6, 7, 8, 9, 10])

In [5]:
len(a)

5

In [6]:
len(b)

5

In [7]:
a[1]

2

In [8]:
a[2]

3

In [9]:
a[3]

4

In [10]:
b[1]

7

In [11]:
b[2]

8

In [12]:
b[3]

9

In [13]:
a

array('i', [1, 2, 3, 4, 5])

In [14]:
a.append(10)

In [15]:
a

array('i', [1, 2, 3, 4, 5, 10])

In [16]:
a.remove(10)

In [17]:
a

array('i', [1, 2, 3, 4, 5])

In [18]:
b

array('i', [6, 7, 8, 9, 10])

In [19]:
b.append(20)

In [20]:
b

array('i', [6, 7, 8, 9, 10, 20])

In [21]:
b.remove(20)

In [22]:
b

array('i', [6, 7, 8, 9, 10])

In [23]:
a.pop(2)

3

In [24]:
b.pop(2)

8

In [25]:
a[::1]

array('i', [1, 2, 4, 5])

In [26]:
a[::-1]

array('i', [5, 4, 2, 1])

In [27]:
b[::1]

array('i', [6, 7, 9, 10])

In [28]:
b[::-1]

array('i', [10, 9, 7, 6])

In [29]:
a.index(2)

1

In [32]:
b.index(9)

2

In [34]:
b.index(10)

3

In [35]:
a.index(4)

2

# Numpys
* pip3 install numpy

In [36]:
import numpy as np

In [37]:
a=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [38]:
a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [39]:
b=np.array([[2,4,6],[8,10,12],[14,16,18]])

In [40]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [41]:
a.dtype

dtype('int32')

In [42]:
b.dtype

dtype('int32')

In [43]:
a.size

9

In [44]:
b.size

9

In [45]:
a[:3]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [46]:
a[:2]

array([[9, 8, 7],
       [6, 5, 4]])

In [47]:
a[:1]

array([[9, 8, 7]])

In [48]:
b[:3]

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [49]:
b[:2]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [50]:
b[:1]

array([[2, 4, 6]])

In [51]:
b[:-1]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [52]:
a[:-1]

array([[9, 8, 7],
       [6, 5, 4]])

In [53]:
a-b

array([[  7,   4,   1],
       [ -2,  -5,  -8],
       [-11, -14, -17]])

In [54]:
a+b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [55]:
a*b

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

In [56]:
a/b

array([[4.5       , 2.        , 1.16666667],
       [0.75      , 0.5       , 0.33333333],
       [0.21428571, 0.125     , 0.05555556]])

In [57]:
type(b)

numpy.ndarray

In [58]:
type(a)

numpy.ndarray

In [59]:
a.ndim

2

In [60]:
b.shape

(3, 3)

In [61]:
a.shape

(3, 3)

In [62]:
c=np.zeros((2,2))

In [63]:
c

array([[0., 0.],
       [0., 0.]])

In [64]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float')

In [65]:
d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [66]:
a.max()

9

In [67]:
b.min()

2

In [68]:
a.min()

1

In [69]:
b.max()

18

In [70]:
a.max(axis=1)

array([9, 6, 3])

In [71]:
a.sum()

45

In [72]:
b.sum()

90

In [73]:
a.sort(axis=1)

In [74]:
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [75]:
np.diag(a)

array([7, 5, 3])

In [76]:
np.diag(b)

array([ 2, 10, 18])

In [77]:
np.sqrt(a)

array([[2.64575131, 2.82842712, 3.        ],
       [2.        , 2.23606798, 2.44948974],
       [1.        , 1.41421356, 1.73205081]])

In [78]:
np.sqrt(b)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162],
       [3.74165739, 4.        , 4.24264069]])

In [79]:
np.trace(a)

15

In [80]:
np.trace(b)

30

In [81]:
a+b

array([[ 9, 12, 15],
       [12, 15, 18],
       [15, 18, 21]])

In [82]:
c.max()

0.0

In [83]:
d.max()

9.0

In [84]:
d.min()

1.0

In [85]:
c.min()

0.0